### PR TITLE
Notification Added 

### LINKED ISSUE #16: Show notification along with sound
**Is your feature request related to a problem? Please describe.**
It is possible that laptop is on mute and I am not able to hear the alert.

**Describe the solution you'd like**
A notification through the browser will solve the problem.

**Describe alternatives you've considered**
None

**Additional context**
None

I can open a simple PR for this. The idea is to ask for notification permission on load. Modify the `play` function to show notification along with playing a sound.

### PR DESCRIPTION
**Pull request by Nikhil27b**
This issue was fixed #16 I added on the notification when slot is found also no slot or slots are full then its show various notification also I made some changes in the HTML instead of use number in input I change into the tel and also add a max-length in the input.

### CODE REVIEW

**Comment by neelpy** [comment]
Can you resolve conflicts?
Currently, it is showing 11 files changed, something is not right

**Comment by Nikhil27b** [comment]
I don't know how to do that my all change go in conflicting files only

**Comment by neelpy** [comment]
Create a new branch from the `booking`  branch and make your changes there. This is creating more issues than solving.

**Comment by Nikhil27b** [comment]
OK I will do that

**Pull request closed without merging**
