### PR TITLE
Refracted Code

### PR DESCRIPTION
**Pull request by tnb24**
Refracted website and deployed it to [here](https://get-cowin-slot.vercel.app/). Will transfer ownership of vercel project to the repository owner if the pull request is accepted, If not i will delete the project.

I will add some css in future pull requests

### CODE REVIEW

**Comment by neelpy** [comment]
I get the other changes. Why have you removed google analytics?

**Comment by tnb24** [comment]
Ooh yes! I don't think a website like this should have google analytics. It does not have that kind of traffic and anyone who will browse through the code will think the same.There is no need for developers to support google tracking people and you can see the criticism of Audacity when they tried to put analytics in their project.

Though if you have a problem I can add it again!

**Comment by neelpy** [comment]
It's just that I can't know how many people are using this without that. And when I see that number I can get an idea of how many people are using it. If the number is growing, I can invest some time to improve it, otherwise I can shift my focus from this.

**Comment by tnb24** [comment]
added analytics back
will be adding some styling today

**Comment by tnb24** [comment]
also removed the api key from script.js and added it as an .env variable in vercel

**Comment by neelpy** [comment]
Just a had a look at the Audacity PR. Do you know any tool which can just show the number of users on the website itself.

**Comment by neelpy** [comment]
> also removed the api key from script.js and added it as an .env variable in vercel

Will I be able to keep the project hosted on GitHub pages as well, after using vercel?

**Comment by tnb24** [comment]
> Just a had a look at the Audacity PR. Do you know any tool which can just show the number of users on the website itself.

I couldn't find anything like google analytics which shows the number of users on a website for free. All other tools are like 90 dollars or so.

> Will I be able to keep the project hosted on GitHub pages as well, after using vercel?

no, as github pages doesnt support directories but thats not a problem as i can transfer the vercel project to you

**Comment by neelpy** [comment]
It supports directories

**Comment by tnb24** [comment]
Oh then yes ofcourse!

**Comment by tnb24** [comment]
Also, I think you will have to host it on github pages if you want ownership of the domain, to transfer a project in vercel you have to make a team which costs like 20 dollars

**Comment by neelpy** [comment]
Okay, the primary hosting is the GitHub pages one anyway. Because I have shared it on social media and most of the users use that link only.

Also, I don't get the benefits of vercel. Like, its best link address does not feel like a good short link.

**Comment by neelpy** [comment]
> also removed the api key from script.js and added it as an .env variable in vercel

This was not meant to be secured, and it will affect the github pages hosting, so reverting this.

**Pull request merged**
